In [1]:
(5, 7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [4]:
(5, )

(5,)

In [5]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a+ list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [8]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [9]:
import numpy as np

[1, 2, 3], [2, 3, 4]

([1, 2, 3], [2, 3, 4])

In [12]:
import numpy as np

l = [[1, 2, 3], [2, 3, 4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [13]:
import numpy as np
np.random.randn(10, 5)


array([[ 0.53973063,  0.56015684, -1.46759404,  0.34589758, -0.33524903],
       [ 0.57921555,  0.75370986,  0.68987435,  0.71361914,  0.3254653 ],
       [ 0.60055237, -0.03066355,  0.84673267,  0.78116482,  0.64359537],
       [-0.6643706 , -0.19752882,  0.37730379, -0.87016398,  0.75636795],
       [-0.01960191, -0.56012922,  1.08095354,  0.96302241,  0.91801439],
       [ 0.00859323,  0.4593865 ,  0.74003772, -1.88072027,  0.5911561 ],
       [-0.9832764 ,  0.54875804, -0.31180021, -0.12324519,  0.19724408],
       [ 1.55216317,  0.87625408,  1.5849942 ,  1.20142955,  0.52984242],
       [ 0.87644412,  0.73118949,  1.03955802,  0.77575667, -1.50028443],
       [ 1.07245514,  0.75126555,  1.04521285,  0.73404785, -0.94511331]])

In [23]:
#50個學生, 每個學生有五個分數(50-100)
import numpy as np
scores = np.random.randint(50, 101, size = (50, 5)) # 101 不包含
scores

array([[ 75,  67,  52,  50,  93],
       [ 86,  62,  94,  95,  89],
       [ 58,  80,  79,  58,  84],
       [ 96,  88,  94,  73,  52],
       [ 92,  73,  94,  65,  77],
       [ 86,  66,  92,  77,  50],
       [ 96,  76,  96,  70,  59],
       [ 77,  89,  98,  92,  73],
       [ 90,  71,  93,  68,  56],
       [100,  81,  61,  95,  77],
       [ 71,  93,  98,  54,  64],
       [ 66,  64,  60,  91,  71],
       [ 73,  72,  56,  99,  67],
       [ 85,  99,  53,  72,  77],
       [ 57,  87,  92, 100,  71],
       [ 50, 100,  90,  50,  62],
       [ 55,  76,  52,  65,  88],
       [ 85,  98,  59,  76,  65],
       [ 50,  76,  81,  81,  52],
       [ 86,  97,  56,  64,  88],
       [ 86,  98,  79,  76,  67],
       [ 71,  86,  60,  56,  84],
       [ 56,  80,  91,  63,  57],
       [ 76,  88,  76,  63,  80],
       [100,  74,  86,  84,  88],
       [ 78,  60,  94,  97,  93],
       [ 55,  84,  53,  68,  86],
       [ 85,  65,  65,  82,  61],
       [ 58,  57,  50,  89,  65],
       [ 66,  

In [31]:
#50個學生, 每個學生有五個分數(50-100)
#第一個學生
scores[0,:]
#前五個學生
scores[:5, :]
# #最後五個學生
scores[-5:, :]

array([[96, 63, 70, 62, 70],
       [65, 50, 88, 84, 86],
       [55, 90, 79, 98, 90],
       [56, 68, 81, 86, 75],
       [98, 60, 63, 61, 63]])

In [32]:
#全班第一科的分數
scores[:, 0]

array([ 75,  86,  58,  96,  92,  86,  96,  77,  90, 100,  71,  66,  73,
        85,  57,  50,  55,  85,  50,  86,  86,  71,  56,  76, 100,  78,
        55,  85,  58,  66,  74,  69,  79,  92,  84,  63,  89,  63,  70,
        86,  70,  67,  54,  92,  99,  96,  65,  55,  56,  98])

In [26]:
#全班第二科的分數
scores[:, 1]

array([ 67,  62,  80,  88,  73,  66,  76,  89,  71,  81,  93,  64,  72,
        99,  87, 100,  76,  98,  76,  97,  98,  86,  80,  88,  74,  60,
        84,  65,  57,  50,  81,  92,  80,  61, 100,  80,  57,  99,  99,
        55,  51,  54,  74,  71,  85,  63,  50,  90,  68,  60])

In [28]:
#每位學生的總分
total = scores[:, 0] + scores[:, 1] + scores[:, 2] + scores[:, 3] + scores[:, 4]
total

array([337, 426, 359, 403, 401, 371, 397, 429, 378, 414, 380, 352, 367,
       386, 407, 352, 336, 383, 340, 391, 406, 357, 347, 383, 432, 422,
       346, 358, 319, 348, 414, 413, 369, 372, 392, 342, 327, 374, 394,
       325, 320, 314, 339, 356, 468, 361, 373, 412, 366, 345])

In [33]:
#使用統計的方法
#美個學生總分
np.sum(scores, axis = 1)

array([337, 426, 359, 403, 401, 371, 397, 429, 378, 414, 380, 352, 367,
       386, 407, 352, 336, 383, 340, 391, 406, 357, 347, 383, 432, 422,
       346, 358, 319, 348, 414, 413, 369, 372, 392, 342, 327, 374, 394,
       325, 320, 314, 339, 356, 468, 361, 373, 412, 366, 345])

In [35]:
#每個學生平均
np.mean(scores, axis=1)


array([67.4, 85.2, 71.8, 80.6, 80.2, 74.2, 79.4, 85.8, 75.6, 82.8, 76. ,
       70.4, 73.4, 77.2, 81.4, 70.4, 67.2, 76.6, 68. , 78.2, 81.2, 71.4,
       69.4, 76.6, 86.4, 84.4, 69.2, 71.6, 63.8, 69.6, 82.8, 82.6, 73.8,
       74.4, 78.4, 68.4, 65.4, 74.8, 78.8, 65. , 64. , 62.8, 67.8, 71.2,
       93.6, 72.2, 74.6, 82.4, 73.2, 69. ])