In [1]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = []
for i in values:
    new_values.append(i*multiply)

new_values

[3, 6, 9, 12, 15]

In [2]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = [i*multiply for i in values]
new_values

[3, 6, 9, 12, 15]

In [6]:
import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
multiply = 3
values_array * multiply

array([ 3,  6,  9, 12, 15])

In [10]:
import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
multiply = 3
values_array * multiply
values_array ** 2 * 3.14159

array([ 3.14159, 12.56636, 28.27431, 50.26544, 78.53975])

In [11]:
import numpy as np
np.random.randint(50,100,size=(50,5))

array([[78, 71, 51, 86, 72],
       [74, 84, 99, 98, 81],
       [77, 55, 78, 61, 88],
       [53, 51, 96, 71, 52],
       [89, 64, 67, 70, 80],
       [64, 65, 58, 79, 98],
       [53, 50, 69, 83, 72],
       [86, 72, 71, 79, 76],
       [57, 87, 69, 60, 71],
       [72, 65, 87, 79, 55],
       [63, 79, 97, 81, 55],
       [78, 73, 71, 84, 52],
       [99, 78, 97, 57, 84],
       [95, 77, 92, 73, 81],
       [96, 62, 96, 88, 91],
       [89, 73, 51, 77, 68],
       [82, 67, 74, 64, 64],
       [99, 51, 71, 63, 56],
       [59, 54, 83, 79, 50],
       [52, 68, 90, 93, 50],
       [91, 89, 96, 66, 98],
       [95, 69, 56, 83, 69],
       [81, 93, 71, 90, 55],
       [64, 79, 56, 58, 72],
       [90, 55, 85, 94, 93],
       [77, 66, 75, 70, 61],
       [68, 59, 83, 78, 83],
       [93, 82, 96, 94, 96],
       [97, 52, 91, 83, 77],
       [86, 84, 62, 72, 81],
       [57, 99, 80, 67, 89],
       [66, 96, 60, 58, 61],
       [88, 72, 58, 84, 79],
       [74, 83, 98, 92, 69],
       [59, 52